postgresql_config_version: 0


# (OPTIONAL | Default: 10) integer value. Defines the connection pool size to PostgreSQL.
# Please see https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
# postgresql_connection_pool_size:


# (OPTIONAL | Default: "localhost") string value. Specify the postgresql host url here. For example:
# - "localhost"
# - "192.168.0.1"
# - "<IP to cloud instance>"
# - "example.com"
# postgresql_host:


# (OPTIONAL | Default: 5432) integer value. Specify the port to use when connecting to PostgreSQL instance.
# postgresql_port:


# (COMPULSORY) string value. The PostgreSQL user to use to query the database.
# If the relevant tables are not already created by you, this user should have the 
# ability to create new tables. To see the tables needed, visit: TODO
postgresql_user: "root"


# (COMPULSORY) string value. Password for the PostgreSQL instance. If you do not have a password
# make this an empty string.
postgresql_password: "root"


# (OPTIONAL | Default: "supertokens") string value. The database name to store SuperTokens related data.
# postgresql_database_name:


# (OPTIONAL | Default: "key_value") string value. Specify the name of the table that will store secret keys
# and app info necessary for the functioning sessions.
# postgresql_key_value_table_name:


# (OPTIONAL | Default: "session_info") string value. Specify the name of the table that will store the
# session info for users.
# postgresql_session_info_table_name:

# (OPTIONAL | Default: "emailpassword_users") string value. Specify the name of the table that will store the
# user information, along with their email and hashed password.
# postgresql_emailpassword_users_table_name:

# (OPTIONAL | Default: "emailpassword_pswd_reset_tokens") string value. Specify the name of the table that will
# store the password reset tokens for users.
# postgresql_emailpassword_pswd_reset_tokens_table_name:

# (OPTIONAL | Default: "emailverification_tokens") string value. Specify the name of the table that will
# store the email verification tokens for users.
# postgresql_emailverification_tokens_table_name:

# (OPTIONAL | Default: "emailverification_verified_emails") string value. Specify the name of the table that will
# store the verified email addresses.
# postgresql_emailverification_verified_emails_table_name: