version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  test:
    docker:
      - image: rishabhpoddar/supertokens_postgresql_plugin_test
    resource_class: large
    steps:
      - add_ssh_keys:
          fingerprints:
            - "14:68:18:82:73:00:e4:fc:9e:f3:6f:ce:1d:5c:6d:c4"
      - checkout
      - run:
          name: update postgresql max_connections
          command: |
            sed -i 's/^#*\s*max_connections\s*=.*/max_connections = 10000/' /etc/postgresql/9.5/main/postgresql.conf
      - run:
          name: starting postgresql
          command: |
            (cd / && ./runPostgreSQL.sh)
      - run:
          name: create databases
          command: |
            psql -c "create database st0;"
            psql -c "create database st1;"
            psql -c "create database st2;"
            psql -c "create database st3;"
            psql -c "create database st4;"
            psql -c "create database st5;"
            psql -c "create database st6;"
            psql -c "create database st7;"
            psql -c "create database st8;"
            psql -c "create database st9;"
            psql -c "create database st10;"
            psql -c "create database st11;"
            psql -c "create database st12;"
            psql -c "create database st13;"
            psql -c "create database st14;"
            psql -c "create database st15;"
            psql -c "create database st16;"
            psql -c "create database st17;"
            psql -c "create database st18;"
            psql -c "create database st19;"
            psql -c "create database st20;"
            psql -c "create database st21;"
            psql -c "create database st22;"
            psql -c "create database st23;"
            psql -c "create database st24;"
            psql -c "create database st25;"
            psql -c "create database st26;"
            psql -c "create database st27;"
            psql -c "create database st28;"
            psql -c "create database st29;"
            psql -c "create database st30;"
            psql -c "create database st31;"
            psql -c "create database st32;"
            psql -c "create database st33;"
            psql -c "create database st34;"
            psql -c "create database st35;"
            psql -c "create database st36;"
            psql -c "create database st37;"
            psql -c "create database st38;"
            psql -c "create database st39;"
            psql -c "create database st40;"
            psql -c "create database st41;"
            psql -c "create database st42;"
            psql -c "create database st43;"
            psql -c "create database st44;"
            psql -c "create database st45;"
            psql -c "create database st46;"
            psql -c "create database st47;"
            psql -c "create database st48;"
            psql -c "create database st49;"
            psql -c "create database st50;"
      - run:
          name: running tests
          command: (cd .circleci/ && ./doTests.sh)
      - slack/status

workflows:
  version: 2
  tagged-build:
    jobs:
      - test:
          context:
            - slack-notification
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/